'use strict';

// Imports

const Lab = require('lab');
const Code = require('code');
const Sinon = require('sinon');
const Sut = require('../');

// Test shortcuts

const lab = module.exports.lab = Lab.script();
const describe = lab.describe;
const it = lab.it;
const beforeEach = lab.beforeEach;
const expect = Code.expect;


describe('better-map', () => {

    let test;

    beforeEach((done) => {

        test = new Sut([
            ['one', 1],
            ['two', 2]
        ]);

        return done();
    });

    describe('constructor', () => {

        it('should create a map without entries when called without an iterator', (done) => {

            // Arrange
            const myMap = new Sut();

            // Assert
            expect(myMap.size).to.equal(0);

            return done();
        });

        it('should create a map with entries when called with a valid iterator', (done) => {

            // Arrange
            const myOtherMap = new Sut([
                ['one', 1],
                ['two', 2]
            ]);

            // Assert
            expect(myOtherMap.size).to.equal(2);

            return done();
        });
    });

    describe('entriesArray', () => {

        it('should return an array of key and value as an array in the order they were added into the map', (done) => {

            // Actual
            const actual = test.entriesArray();

            // Assert
            expect(actual).to.equal([['one', 1], ['two', 2]]);

            return done();
        });
    });

    describe('keysArray', () => {

        it('should return the keys as an array in the order they were added into the map', (done) => {

            // Actual
            const actual = test.keysArray();

            // Assert
            expect(actual).to.equal(['one', 'two']);

            return done();
        });
    });

    describe('valuesArray', () => {

        it('should return the values as an array in the order they were added into the map', (done) => {

            // Actual
            const actual = test.valuesArray();

            // Assert
            expect(actual).to.equal([1, 2]);

            return done();
        });
    });

    describe('map', () => {

        it('should call the callback with the expected parameters', (done) => {

            // Arrange
            const mapper = Sinon.stub().returns(0);

            // Actual
            const actual = test.map(mapper);

            // Assert
            expect(actual).to.equal([0, 0]);
            Sinon.assert.calledTwice(mapper);
            Sinon.assert.calledWithExactly(mapper, 1, 'one', test);
            Sinon.assert.calledWithExactly(mapper, 2, 'two', test);

            return done();
        });

        it('should return an array of values generated by the callback function', (done) => {

            // Actual
            const actual = test.map((value, key) => `${key} = ${value}`);

            // Assert
            expect(actual).to.equal(['one = 1', 'two = 2']);

            return done();
        });
    });

    describe('reduce', () => {

        it('should call the callback with the expected parameters when called without initial', (done) => {

            // Arrange
            const reducer = Sinon.stub().returns(0);

            // Actual
            const actual = test.reduce(reducer);

            // Assert
            expect(actual).to.equal(0);
            Sinon.assert.calledTwice(reducer);
            Sinon.assert.calledWithExactly(reducer, undefined, 1, 'one', test);
            Sinon.assert.calledWithExactly(reducer, 0, 2, 'two', test);

            return done();
        });

        it('should call the callback with the expected parameters when called with initial', (done) => {

            // Arrange
            const reducer = Sinon.stub().returns(0);

            // Actual
            const actual = test.reduce(reducer, 1337);

            // Assert
            expect(actual).to.equal(0);
            Sinon.assert.calledTwice(reducer);
            Sinon.assert.calledWithExactly(reducer, 1337, 1, 'one', test);
            Sinon.assert.calledWithExactly(reducer, 0, 2, 'two', test);

            return done();
        });

        it('should return an array of values generated by the callback function', (done) => {

            // Actual
            const actual = test.reduce((pv, cv) => pv + cv, 0);

            // Assert
            expect(actual).to.equal(3);

            return done();
        });
    });
});
